### ISSUE TITLE
Design New Trip Page

### ISSUE THREAD

**Issue by ec-miller** [ec-miller/sht_tracker#2]
#### Technologies:
HTML and CSS (Bootstrap)
#### Aim:
As a user I would like a well designed page where I can log a New Trip. 
#### Getting started:
I've created skeletons of newtrip.html - inside you'll find a list of form elements that are needed on the page. Feel free to inject your personal style to make this page shine, but try to use Bootstrap classes where possible. A list of Start/End Points can be found [here](https://docs.google.com/spreadsheets/d/16fETxJUKElO-DvisVSISU-VrzB3OvKn1hwuee0MNCu8/edit#gid=1711527128).
#### Useful links:
[Bootstrap Forms Documentation](https://getbootstrap.com/docs/4.0/components/forms/)

**Comment by ec-miller** [comment]
http://www.randomsnippets.com/2008/02/21/how-to-dynamically-add-form-elements-via-javascript/  - example of how to dynamically add/remove input fields.

**Comment by Cynth42** [comment]
Hey Eric,
I'm trying to figure out how to stop the add another email button from resizing when it's clicked and how to dynamically remove the email input boxes.  Any ideas?
<img width="1277" alt="screen shot 2018-04-20 at 12 14 51 pm" src="https://user-images.githubusercontent.com/14208716/39062236-f2bbc00a-4494-11e8-8f8d-15cfda6514dd.png">

**Comment by ec-miller** [comment]
Hi Cynthia,

I think the "Add Another E-mail" button keeps getting larger because it is linked to the row that the additional e-mail entry fields are in. I played around with it a bit and I think moving both buttons to the bottom of the form in their own row would be the best way to get around this.
![image](https://user-images.githubusercontent.com/12504026/39075613-2e1490c4-44bc-11e8-8c9b-747da0684d04.png)

Let me know what you think!

I have a couple other notes from checking out the page:
1. I noticed that the class called myEmail[] doesn't seem to link to any CSS, so I think this can be removed from the email fields, unless you were planning to add style there. 

2. The dynamically added email inputs are a different size than the initial e-mail input. To have them size the same, all that is needed is bootstrap form class `class="form-control"` in the newdiv.innerhtml of your newtrip.js file.

3. I like how you put placeholders in the form boxes. I think that it would look good if you removed the titles, since the placeholders tell users what needs to be entered. Removing the titles would allow the design to be a little tighter too. 

Let me know if you would like to add these to the pull request before I merge, otherwise I can make the changes after I merge it. Thanks!

**Comment by Cynth42** [comment]
I added the changes Eric- take a look and let me know what you think before I push
<img width="1278" alt="screen shot 2018-04-20 at 10 46 39 pm" src="https://user-images.githubusercontent.com/14208716/39079662-b10c3d70-44ed-11e8-93cd-c8c9ead3ad99.png">
.

**Comment by ec-miller** [comment]
Thank you for all your work @Cynth42 ! Pull request #9 closes this issue.
