### ISSUE TITLE
Personalize The Trail Page

### ISSUE THREAD

**Issue by ec-miller** [ec-miller/sht_tracker#4]
#### Technologies:
JavaScript and/or jQuery
#### Aim:
As a user I would like to have The Trail Page to show me which trail sections I have completed. 
#### Getting started:
I've created a variable in thetrail.js called ericSections that contains an array of the section numbers that I’ve completed. Use this list to mark those sections in the table that is displayed on The Trail Page. One approach would be the change the background color of those table rows, but feel free to explore and come up with your own way to mark them.

**Comment by tyler-vs** [comment]
hi again, might have a simple solution for this, please take a look at pull request #8 .

**Comment by ec-miller** [comment]
Nice, thanks for tackling this one too @tyler-vs ! Looks good :)

**Comment by tyler-vs** [comment]
thanks @ec-miller , it really builds on the work you added to pull request #6 , so thank you my good sir
