### ISSUE TITLE
Add Summary Stats to The Trail Page

### ISSUE THREAD

**Issue by ec-miller** [ec-miller/sht_tracker#5]
#### Technologies:
HTML and CSS (Bootstrap), JavaScript and/or jQuery
#### Aim:
As a user I would like to have The Trail Page to show me total mileage and my completion percentage, based on the sections that I am displaying with the filters on this page. If I am displaying all sections the total mileage should = 324.1, if I am just displaying Lutsen to Grand Marais it should = 35.2.
#### Getting started:
The element for this data will need to be positions below the filters and above the table on The Trail Page. Use the Miles data point in visible rows to calculate the total mileage displayed at any given time. Make sure that your calculations are responsive to filter button presses so that they match the data displayed in the table. I've created a variable in thetrail.js called ericSections that contains an array of the section numbers that I’ve completed. Use this list to calculate percentage completed.

**Comment by tyler-vs** [comment]
Pull request #6
